"""Core operations for buildlog skill management."""

from buildlog.core.operations import (
    CommitResult,
    CreateEntryResult,
    DiffResult,
    EndSessionResult,
    GauntletAcceptRiskResult,
    GauntletGenerateResult,
    GauntletLoopConfigResult,
    GauntletLoopResult,
    GauntletPromptResult,
    GauntletRulesResult,
    InitResult,
    LearnFromReviewResult,
    ListEntriesResult,
    LogMistakeResult,
    LogRewardResult,
    Mistake,
    OverviewResult,
    PromoteResult,
    RejectResult,
    ReviewIssue,
    ReviewLearning,
    RewardEvent,
    RewardSummary,
    Session,
    SessionMetrics,
    StartSessionResult,
    StatusResult,
    UpdateResult,
    VerifyCheck,
    VerifyResult,
    commit,
    create_entry,
    diff,
    end_session,
    ensure_session,
    find_skills_by_ids,
    gauntlet_accept_risk,
    gauntlet_generate,
    gauntlet_loop_config,
    gauntlet_process_issues,
    gauntlet_rule_lookup,
    generate_gauntlet_prompt,
    get_bandit_status,
    get_experiment_report,
    get_gauntlet_rules,
    get_overview,
    get_posterior_history,
    get_rewards,
    get_session_metrics,
    init_buildlog,
    learn_from_review,
    list_entries,
    log_mistake,
    log_reward,
    promote,
    reject,
    start_session,
    status,
    update_buildlog,
    verify_workflow,
)

__all__ = [
    "StatusResult",
    "PromoteResult",
    "RejectResult",
    "DiffResult",
    "ReviewIssue",
    "ReviewLearning",
    "LearnFromReviewResult",
    "RewardEvent",
    "LogRewardResult",
    "RewardSummary",
    # Session tracking
    "Session",
    "Mistake",
    "SessionMetrics",
    "StartSessionResult",
    "EndSessionResult",
    "LogMistakeResult",
    # Gauntlet loop
    "GauntletLoopResult",
    "GauntletAcceptRiskResult",
    # Entry & overview
    "GauntletRulesResult",
    "OverviewResult",
    "CreateEntryResult",
    "ListEntriesResult",
    "status",
    "promote",
    "reject",
    "diff",
    "find_skills_by_ids",
    "learn_from_review",
    "log_reward",
    "get_rewards",
    # Session tracking operations
    "ensure_session",
    "start_session",
    "end_session",
    "log_mistake",
    "get_session_metrics",
    "get_experiment_report",
    "get_bandit_status",
    "get_posterior_history",
    # Gauntlet loop operations
    "gauntlet_process_issues",
    "gauntlet_rule_lookup",
    "gauntlet_accept_risk",
    # Entry & overview operations
    "get_gauntlet_rules",
    "get_overview",
    "create_entry",
    "list_entries",
    # P0: Gauntlet loop
    "CommitResult",
    "GauntletPromptResult",
    "GauntletLoopConfigResult",
    "commit",
    "generate_gauntlet_prompt",
    "gauntlet_loop_config",
    # P2: Nice-to-have
    "GauntletGenerateResult",
    "InitResult",
    "UpdateResult",
    "gauntlet_generate",
    "init_buildlog",
    "update_buildlog",
    # Workflow verification
    "VerifyCheck",
    "VerifyResult",
    "verify_workflow",
]
