"""Core operations for buildlog skill management."""

from buildlog.core.operations import (
    AcceptedRisk,
    DiffResult,
    EndSessionResult,
    GauntletAcceptRiskResult,
    GauntletLoopResult,
    GauntletState,
    LearnFromReviewResult,
    LogMistakeResult,
    LogRewardResult,
    Mistake,
    PromoteResult,
    RejectResult,
    ReviewIssue,
    ReviewLearning,
    RewardEvent,
    RewardSummary,
    Session,
    SessionMetrics,
    StartSessionResult,
    StatusResult,
    check_gauntlet_freshness,
    diff,
    end_session,
    find_skills_by_ids,
    gauntlet_accept_risk,
    gauntlet_process_issues,
    get_bandit_status,
    get_experiment_report,
    get_rewards,
    get_session_metrics,
    increment_gauntlet_staleness,
    learn_from_review,
    load_gauntlet_state,
    log_mistake,
    log_reward,
    promote,
    record_gauntlet_run,
    reject,
    save_gauntlet_state,
    start_session,
    status,
    track_dirty_file,
)

__all__ = [
    "StatusResult",
    "PromoteResult",
    "RejectResult",
    "DiffResult",
    "ReviewIssue",
    "ReviewLearning",
    "LearnFromReviewResult",
    "RewardEvent",
    "LogRewardResult",
    "RewardSummary",
    # Session tracking
    "Session",
    "Mistake",
    "SessionMetrics",
    "StartSessionResult",
    "EndSessionResult",
    "LogMistakeResult",
    # Gauntlet loop
    "GauntletLoopResult",
    "GauntletAcceptRiskResult",
    "AcceptedRisk",
    "status",
    "promote",
    "reject",
    "diff",
    "find_skills_by_ids",
    "learn_from_review",
    "log_reward",
    "get_rewards",
    # Session tracking operations
    "start_session",
    "end_session",
    "log_mistake",
    "get_session_metrics",
    "get_experiment_report",
    "get_bandit_status",
    # Gauntlet loop operations
    "gauntlet_process_issues",
    "gauntlet_accept_risk",
    # Auto-gauntlet
    "GauntletState",
    "check_gauntlet_freshness",
    "load_gauntlet_state",
    "save_gauntlet_state",
    "increment_gauntlet_staleness",
    "record_gauntlet_run",
    "track_dirty_file",
]
